---
# file: roles/gitbucket/tasks/main.yml
- name: generate hosts files
  lineinfile: dest=/etc/hosts regexp='.*{{ansible_fqdn}}.*' line="{{ansible_default_ipv4.address}} {{ansible_fqdn}} {{ansible_hostname}}" state=present

- name: EPEL install check
  command: rpm -q epel-release
  register: inst_epel
  failed_when: inst_epel.rc not in [0,1]
  changed_when: inst_epel.rc != 0
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: copy EPEL rpm
  copy: src={{epel}} dest=/tmp
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" and inst_epel.rc != 0

- name: EPEL install
  yum: name=/tmp/{{epel}} state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" and inst_epel.rc != 0

- name: packages install
  yum: name={{item}} state=present
  with_items:
    - tomcat
    - httpd

- name: copy gitbucket.war
  copy: src=gitbucket.war dest=/var/lib/tomcat/webapps
  notify: tomcat restart

- name: create gitbucket repo dir
  file: path=/var/lib/gitbucket owner=tomcat group=tomcat state=directory
 
- name: link gitbucket repo for tomcat
  file: src=/var/lib/gitbucket dest=/usr/share/tomcat/.gitbucket owner=tomcat group=tomcat state=link

- name: Apache ServerName setting
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^ServerName" line="ServerName {{ansible_fqdn}}:80" insertafter="^#ServerName" state=present
  notify: httpd restart

- name: enable service
  service: name={{item}} state=started enabled=yes
  with_items:
    - tomcat
    - httpd
